### PR TITLE
fix: utilize cf nameserver, advertise multiaddress

### LINKED ISSUE #55: bug: Multiaddress always points to system default DNS
**Describe the bug**
Instances outside of the local network cannot connect to the nodes as multiaddress specified and encoded in ENR records points to system default DNS. The connection logs upon initialization is confusing for which peer has been successfully connected.

**Expected behavior**
Multiaddress for nodes should specify the exposed address such that peer nodes can connect to them.
-> Routing nodes must either provide an exposed host and port for the construction of multiaddress, or pass in an advertised multiaddress

**Additional context**
Specify nameserver (from cloudflare) for better resolve of the enrtree url

### PR DESCRIPTION
**Pull request by hopeyen**
### Description
- Utilize Cloudflare DNS nameserver for discovery
- Allow users to provide customized multiaddress to advertise to peers
- Update logs to be more accurate for connected peers
- Use exposed IP endpoint 

### Issue link (if applicable)
Closes #55

### CODE REVIEW

File: src/gossip_agent/mod.rs [hunk 1]
```diff
@@ -93,6 +93,7 @@ impl GossipAgent {
         subtopics: Option<Vec<&str>>,
         waku_host: Option<String>,
         waku_port: Option<String>,
+        waku_addr: Option<String>,
```
Comment (axiomatic-aardvark) [inline src/gossip_agent/mod.rs:96]: I think we should rename these three, the end user shouldn't have to care what Waku is, we can call them `graphcast_host`, `graphcast_port`, `node_addr`/`boot_node_addr`, what do you think?

**Review by axiomatic-aardvark — DISMISSED** [review]
One small suggestion otherwise good to go 🚀 This is bulldozer work right here

File: src/gossip_agent/mod.rs (hunk 1 above)
Comment (hopeyen) [reply src/gossip_agent/mod.rs:120]: I wouldn't label them with graphcast, and I think that since they are in the SDK level then those who are developing with the SDK should be aware that waku is the underlying gossip protocol and that they will be communicating through waku nodes?

Comment (axiomatic-aardvark) [reply src/gossip_agent/mod.rs:120]: I still don't think they should be aware that we are using Waku, it's unnecessary cognitive load for the SDK items, especially user-facing ones.  Graphcast should be a black box in that aspect, and to the users it shouldn't matter what underlying gossip protocol we use. If we were to change the protocol for instance, we would want the field names to stay the same

**Review by axiomatic-aardvark — DISMISSED** [review]

**Review by axiomatic-aardvark — APPROVED** [review]
