### PR TITLE
fix: boot node connections

### LINKED ISSUE #291: Messages not being sent/received
messages are not being sent or received by Radios running the latest version of the SDK, this is possibly because the multiple connection failures after adding the discovery network ENR to our boot nodes

### PR DESCRIPTION
**Pull request by cargopete**
### Description
Fixes:
- [x] Disconnect from peers that don't support protocols we need (might need more customisability here, but since our peer id is not in the peers list, getting our local node's protocols isn't that straightforward, we'd need to check the config vars)
- [x] Re-connect only to nodes that support protocols we need
- [x] When sending messages, try sending only to connected peers
- [x] Turning off waku nodes by default (setting level to `Panic`), they are way too noisy

### CODE REVIEW

File: examples/ping-pong/src/main.rs [hunk 1]
```diff
@@ -107,7 +107,7 @@ async fn main() {
         None,
         Some(true),
         // Example ENR address
-        Some(vec![String::from("enr:-JK4QBcfVXu2YDeSKdjF2xE5EDM5f5E_1Akpkv_yw_byn1adESxDXVLVjapjDvS_ujx6MgWDu9hqO_Az_CbKLJ8azbMBgmlkgnY0gmlwhAVOUWOJc2VjcDI1NmsxoQOUZIqKLk5xkiH0RAFaMGrziGeGxypJ03kOod1-7Pum3oN0Y3CCfJyDdWRwgiMohXdha3UyDQ")]),
+        Some(vec![String::from("enr:-P-4QJI8tS1WTdIQxq_yIrD05oIIW1Xg-tm_qfP0CHfJGnp9dfr6ttQJmHwTNxGEl4Le8Q7YHcmi-kXTtphxFysS11oBgmlkgnY0gmlwhLymh5GKbXVsdGlhZGRyc7hgAC02KG5vZGUtMDEuZG8tYW1zMy53YWt1djIucHJvZC5zdGF0dXNpbS5uZXQGdl8ALzYobm9kZS0wMS5kby1hbXMzLndha3V2Mi5wcm9kLnN0YXR1c2ltLm5ldAYfQN4DiXNlY3AyNTZrMaEDbl1X_zJIw3EAJGtmHMVn4Z2xhpSoUaP5ElsHKCv7hlWDdGNwgnZfg3VkcIIjKIV3YWt1Mg8")]),
```
Comment (hopeyen) [inline examples/ping-pong/src/main.rs]: which one is this? can we have the string live in a variable that has an appropriate name?

File: examples/ping-pong/src/main.rs [hunk 2]
```diff
@@ -193,6 +193,8 @@ async fn main_loop(agent: &GraphcastAgent, running: Arc<AtomicBool>) {
                 .await
             {
                 error!(error = tracing::field::debug(&e), "Failed to send message");
+            } else {
+                info!("Ping message sent successfully")
```
Comment (hopeyen) [inline examples/ping-pong/src/main.rs]: perhaps lower the level for this to debug? either way is okay I guess, since this is just ping-pong

File: src/graphcast_agent/waku_handling.rs [hunk 3]
```diff
@@ -496,25 +488,35 @@ pub fn peers_data(
...
+        let contains_lightpush = peer
+            .protocols()
+            .iter()
+            .any(|p| p == "/vac/waku/lightpush/2.0.0-beta1");
+        let contains_relay = peer
+            .protocols()
+            .iter()
+            .any(|p| p == "/vac/waku/relay/2.0.0");
+
+        if contains_filter && contains_lightpush && contains_relay {
```
Comment (hopeyen) [inline src/graphcast_agent/waku_handling.rs]: this might not exactly match the requirement for what the local node wants. For instance we typically expect relay to be off locally, so this would be restricting most of the peers. Can we condition with `WakuNodeConfig`'s fields like `relay` and `filter`?

File: src/graphcast_agent/mod.rs [hunk 4]
```diff
@@ -208,6 +208,8 @@ pub struct GraphcastAgent {
     /// Upon receiving a valid waku signal event of Message type, sender send WakuMessage through mpsc.
     //TODO: currently agent returns the receiver to radio operator, such that radio handler can process WakuMessage however they want. Ideally we should keep WakuMessage within graphcast agent, but for now radio operator is required call generic decode with the specified types. Later we investigate an approach to dynamically register the types during runtime
     pub sender: Arc<SyncMutex<Sender<WakuMessage>>>,
+    /// Keeps track of whether Filter protocol is enabled, if false -> we're using Relay protocol
+    pub filter_protocol_enabled: bool,
```
Comment (hopeyen) [inline src/graphcast_agent/mod.rs:212]: I guess it's not possible to access waku node config settings with the node_handle? can we open an feature request issue for waku please

**Review by hopeyen — APPROVED** [review]

File: src/graphcast_agent/mod.rs (hunk 4 above)
Comment (cargopete) [reply src/graphcast_agent/mod.rs:212]: for sure, also it would be good to have the Display trait on the node handle struct so we can debug easier

Comment (cargopete) [reply src/graphcast_agent/mod.rs:212]: https://github.com/waku-org/waku-rust-bindings/issues/80
